### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [Kongsea/Resize-to-fixed-size-keeping-aspect-ratio#1]
Greetings, @Kongsea 

I'm an open source enthusiast, and just noticed you've just started this project!
I wanted to collaborate! I'd like to propose a logo _for free_
If thats something that might interest you, let me know!

Graphic Designer - Luigi.
Cheers!

**Comment by Kongsea** [comment]
Thank you for your proposal.
But this project is just a toy one, it's not a complete project.
